name: 'package-lint'
on: { push: { paths: [ '**.el' ] } }
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: ["snapshot"]
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cat <(jq -r '.nodes.root.inputs | map(.) | .[]' .nomake/flake.lock) \
            <(jq -r 'keys | .[]' .nomake/archive.lock) \
            <(echo 'package-lint') \
            | xargs emacs -batch -l package --eval \
            "(progn
                (push '(\"melpa\" . \"https://melpa.org/packages/\")
                      package-archives)
                (package-initialize)
                (when command-line-args-left
                  (package-refresh-contents))
                (dolist (package-name command-line-args-left)
                  (let ((package (intern package-name)))
                     (when (and package
                                (not (memq package
                                           '(org-starter org-starter-swiper))))
                       (package-install (cadr (assq package 
                                                    package-archive-contents)))))))"
    - name: Byte-compile
      if: ${{ true }}
      run: |
        emacs -batch -l bytecomp -l package --eval "(push '(\"melpa\" . \"https://melpa.org/packages/\") package-archives)" --eval "(package-initialize)" -L . \
          --eval "(setq byte-compile-error-on-warn t)" \
          -f batch-byte-compile 'org-starter.el' 'org-starter-swiper.el'
    - name: Run package-lint
      run: |
        emacs -l package --eval "(push '(\"melpa\" . \"https://melpa.org/packages/\") package-archives)" --eval "(package-initialize)" -L . -batch -l package-lint \
          -f package-lint-batch-and-exit 'org-starter.el'

        emacs -l package --eval "(push '(\"melpa\" . \"https://melpa.org/packages/\") package-archives)" --eval "(package-initialize)" -L . -batch -l package-lint \
          -f package-lint-batch-and-exit 'org-starter-swiper.el'
