jobs:
  lint:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v8
      - uses: actions/checkout@v1
      - uses: akirak/emacs-package@v1
      - name: 'Lint (with Emacs version: latest)'
        run: melpa-check lint -e latest org-starter-swiper
  tests:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v8
      - uses: actions/checkout@v1
      - uses: akirak/emacs-package@v1
      - name: 'Byte-compile (with Emacs version: all)'
        run: melpa-check byte-compile -e all org-starter-swiper
      - name: 'Test using buttercup (with Emacs version: all)'
        run: melpa-check buttercup -e all org-starter-swiper
name: org-starter-swiper CI
'on':
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.org'
